#
#spring.datasource.url=jdbc:h2:mem:kc_db
#spring.datasource.driverClassName=org.h2.Driver
#spring.h2.console.enabled=true



#spring:
#  datasource:
#    url: jdbc:h2:mem:kc_db
#    driverClassName: org.h2.Driver
#  h2:
#    console:
#      enabled: true

server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tp_spring_horizon?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak:
#            client-id: health-care-back
#            client-secret: U4CANO33sgLXQXE0Xasj5NkhpLSotd4H
#            authorization-grant-type: authorization_code
#            scope: openid
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8080/realms/health-care
#            user-name-attribute: preferred_username
#      resourceserver:
#        jwt:
#          jwk-set-uri: http://localhost:8080/realms/health-care

#          keycloak:
#            realm: realm-test
#            resource: client-test
#            auth-server-url: http://localhost:8080
#            bearer-only: true
#            ssl-required: none


#spring.datasource.url=jdbc:h2:mem:kc_db
#spring.datasource.driverClassName=org.h2.Driver
#spring.h2.console.enabled=true
#
#spring.security.oauth2.client.registration.keycloak.client-id=client-test
#spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.keycloak.scope=openid
#
#spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8080/realms/SpringBootKeycloak
#spring.security.oauth2.client.provider.keycloak.user-name-attribute=admin
#
#server.port=9090
#
#keycloak.realm=realm-test
#keycloak.resource=client-test
#keycloak.auth-server-url=http://localhost:8080
#keycloak.bearer-only=true
#keycloak.ssl-required=none
##  secret: mNNqsKejsDiVDPYfnV57LSNWqCturQNo
##  public-client: false
